### ISSUE TITLE
when will you do performance test?

### ISSUE THREAD

**Issue by wtj0906** [rsocket/rsocket-py#54]
when will you do performance test? I find that errors occur when I query big size data from an rsocket java server.

**Comment by gabis-precog** [comment]
@wtj0906 

Please phrase this as a bug or as a feature request. 
Please provide examples. Preferably as a test to reproduce.

On a more personal note, as you do not have any contact details on your github page, i will air dirty laundry here:

This is an open source project and i am a volunteer.
Please stop opening tickets with "when will you ...".

Or to rephrase along the lines of your bug report: "When will you start acting professionally ? I find I get annoyed when people ask me when i will do something instead of giving detailed information which will actually help."

If you insist of continuing opening bugs with that tone, I will simply close them with "whenever I feel like it", as that would be a correct resolution of the bug.
