### ISSUE TITLE
Arrow data MIME support

### ISSUE THREAD

**Issue by wtj-jtw** [rsocket/rsocket-py#60]
I recently used Apache Arrow in my project. Apache Arrow may be a de facto standard for data transfer on the wire in the future.

> https://arrow.apache.org/faq/

> https://www.iana.org/assignments/media-types/application/vnd.apache.arrow.stream

> https://www.iana.org/assignments/media-types/application/vnd.apache.arrow.file

Will rsocket support these in the future?

This may made rsocket more **powerful**.

**Comment by jell-o-fishi** [comment]
I am unclear on what support is required.

RSocket already allows for custom mimetypes by explicitly specifying it instead of using the preset ones.

If you have further questions I think the rsocket slack is a better place for that, as I don't think this is a question specifically for the python implementation.

If you still think this is a python specific issue i would love to see some use case so I can understand.

**Comment by jell-o-fishi** [comment]
The supported mime type list is part of an extension specification (as i understand it). those mimetypes would need to be added there before they are added to the python specific implementation. again you should raise this in the rsocket slack.

**Comment by jell-o-fishi** [comment]
See: https://github.com/rsocket/rsocket/blob/master/Extensions/WellKnownMimeTypes.md

**Comment by wtj-jtw** [comment]
@jell-o-fishi  Thanks for your quick reply, i will learn more about specifying custom mimetypes before i get back here.

**Comment by jell-o-fishi** [comment]
@wtj-jtw see RSocketClient and RSocketServer arguments. metadata_encoding and data_encoding are both Union[bytes, WellKnownMimeTypes]. they can be one of the enums, or explicitly the mimetype, for example: `b'vnd.apache.arrow.stream'`
